# context path
server.servlet.context-path=/erp_base
server.port=8081

spring.mvc.hiddenmethod.filter.enabled=true

#connection setting
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=localdb;encrypt=false
spring.datasource.username=sa
spring.datasource.password=mssql8907
spring.jpa.database=sql-server

# jpa settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

system.default.locale=zh_TW

#javaMail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ryanimay840121@gmail.com
spring.mail.password=lnst qkgw gumh hwpw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#thymmeleaf
spring.thymeleaf.prefix=classpath:
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

security.password=12345

#quartz
spring.quartz.job-store-type=jdbc
spring.quartz.overwrite-existing-jobs=true
spring.quartz.properties.org.quartz.scheduler.instanceName = ErpScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId = AUTO
spring.quartz.properties.org.quartz.threadPool.threadCount = 10
spring.quartz.properties.org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate