  drop table attend
  drop table client
  drop table client_notifications
  drop table client_roles
  drop table department_role
  drop table department
  drop table job
  drop table leave
  drop table notification
  drop table performance
  drop table permission
  drop table procurement
  drop table project
  drop table QRTZ_BLOB_TRIGGERS
  drop table QRTZ_CALENDARS
  drop table QRTZ_CRON_TRIGGERS
  drop table QRTZ_FIRED_TRIGGERS
  drop table QRTZ_JOB_DETAILS
  drop table QRTZ_LOCKS
  drop table QRTZ_PAUSED_TRIGGER_GRPS
  drop table QRTZ_SCHEDULER_STATE
  drop table QRTZ_SIMPLE_TRIGGERS
  drop table QRTZ_SIMPROP_TRIGGERS
  drop table QRTZ_TRIGGERS
  drop table quartz_job
  drop table role
  drop table role_permission
  drop table menu
  drop table menu_role
  drop table salary
  drop table tracking_job
  drop table log